### ISSUE TITLE
Compatibility with the PID concept

### ISSUE THREAD

**Issue by fbaumgardt** [distributed-text-services/collection-api#13]
I'm copying this over from an email to Bridget:

> Studying the specifications of PID schemes such as ARK and DOI it occurs to me that we will need to be much more rigorous about persistence than I previously thought. If we want to be compatible with established schemes or even use them, mutable payload for PIDs is simply not possible. I had that sense during the plenary and my readings today confirmed it.
> 
> This doesn’t mean that we cannot a) maintain a (canonical) reference to the most recent version of an abstract object, or b) version the abstract object. But the reference in a) cannot be called a PID and the versioning in b) will have to be expressed as next/previous relations between PID-referenced concrete and immutable objects.
> 
> In practice, this doesn’t change a whole lot, except that citations shouldn’t happen on abstract objects (e.g. <notP-ID>) but concrete objects (e.g. <notP-ID>@62e4b09d or <notP-ID>@2016-03-15/16:03:45), and we stop calling CTS URNs PIDs. CTS URNs + version-suffix could be a PID though. We could represent editions/milestones with a particular formatting of the version string (e.g. hash vs. version number), to improve the legibility for human(ist)s.
> 
> I suggest that we keep this in mind during the DTS design phase.

I should add that the usage of _CTS_ in the text above reflects the way it's been talked about in the Open Philology ecosystem and as I understand it, Chris and Neel have used the term in a manner that _is_ compatible with the common definition of PIDs.

**Comment by PonteIneptique** [comment]
@fbaumgardt I honnestly have no idea how to mark this issue :disappointed:

**Comment by fbaumgardt** [comment]
I'd say it's mostly Update (Access type), and looking at the use cases I chose Collection (Data Type) but it's probably a wider topic.

**Comment by balmas** [comment]
As the spec really supports any sort of identifier, and doesn't impose any, I'm closing this as implemented. It may likely resurface in references api though so I'll make a note of it there.
