### ISSUE TITLE
A user story designed to illustrate the need for a "Manifestation" level resource

### ISSUE THREAD

**Issue by jeffreycwitt** [distributed-text-services/collection-api#18]
A user story designed to illustrate the need for a "Manifestation" level resource.
# Vocabulary Background
## CTS documentation states:

> Within a text group, a CTS URN’s work is a conceptual entity, like the FRBR work: it is an abstract idea of the content expressed in all versions of a work, in the original language or in translation. The work may optionally be identified with increasing specificity as versions (translation or edition), or exemplars (individual physical copies). The CTS URN’s version corresponds to the “expression” in the FRBR model, while exemplars correspond to “items” in FRBR parlance. (http://www.homermultitext.org/hmt-doc/cite/cts-urn-overview.html)

What is not mentioned here is a resource mapping to the FRBR "Manifestation" Resource.
## CTS FRBR Terminology Mapping
- CTS TextGroup = FRBR WorkGroup 
- CTS Work = FRBR Work = "Work is a "distinct intellectual or artistic creation." For example, Beethoven's Ninth Symphony apart from all ways of expressing it is a work. When we say, "Beethoven's Ninth is magnificent!" we generally are referring to the work.
- CTS Version = FRBR Expression = "is "the specific intellectual or artistic form that a work takes each time it is 'realized.'"[1] An expression of Beethoven's Ninth might be each draft of the musical score he writes down (not the paper itself, but the music thereby expressed)."
  - [JW: I see the main problem here. I think CTS Version should be identified with FRBR Manifestation not FRBR Expression. There can be several CTS version / FRBR manifestations of a particular expression. Many different editors can produce a version of a particular expression of a work. For example: several editors could produce different editions of a particular "draft" of Beethoven's 9th symphony.] 
- CTS ??? = FRBR Manifestation = "the physical embodiment of an expression of a work. As an entity, manifestation represents all the physical objects that bear the same characteristics, in respect to both intellectual content and physical form."
- CTS Exemplar = FRBR Item (a single book in a single library of a particular Manifestation) = "Item is "a single exemplar of a manifestation."
# Use Case Background

Adam Wodeham's Oxford Ordinatio Commentary on the Sentences is a FRBR Work as I understand it. 

But this work was _expressed_ by Wodeham in the 1330's as his written version. For the moment let us call this his "Reportatio."

But this same work was _expressed_ as an "abbreviatio" by Henry Totting of Oyta, known as the "Abbreviatio."

This is the same FRBR Work. Adam Wodeham is the author or creator in both cases and they contain the same content. But the content is expressed differently.

The "Reportatio" was _expressed_ by Wodeham himself while the "Abbreviatio" was expressed by Henry Totting of Oyta.

We cannot simply call these CTS Versions or FRBR Manifestations because each of these _Expressions_ will have their own versions/editions and they themselves still correspond to the idea of the particular expression, not any material instantiation of that ideal expression. 

Further, in 1516 John Mair produced the 1516 printed edition (FRBR Manifestation) (which I see as a CTS Version) of the "Abbreviatio" FRBR Expression of Adam Wodeham's FRBR/CTS Work the "Oxford Ordinatio."

This 1516 manifestation will be printed in several books which are FRBR Items or CTS Exemplars. 

Someone might produce a diplomatic transcription of this FRBR Manifestation, and I think this should sit along side any individual printed book as another FRBR Item or CTS Exemplar. (Although it is a digital instantiation rather than a material one. I refer to these Items/Exemplars below as "transcriptions")

At the same time there are several manuscript versions of the Wodeham Abbreviatio. These are also FRBR Manifestations / CTS Versions of the same FRBR Expression, but they will typically only have a singular CTS Exemplar / FRBR Item (given the fact that they are manuscripts and are not reproducible in the way printed books are).

Here is a visualization of this mapping: [https://github.com/jeffreycwitt/scta-ontology/blob/master/UeliWodeModel.pdf](https://github.com/jeffreycwitt/scta-ontology/blob/master/UeliWodeModel.pdf)
# Direct Use Cases

Let's imagine I wanted to retrieve an edition with an accompanying transcription of Adam Wodeham's Oxford Ordinatio for statistical purposes

If I queried Wodeham's Ordinatio and I simply received back a list of all CTS Versions that have an accompanying transcription, I would be presented with the 1522 edition (made from Henry Totting of Oyta's Abbreviatio) alongside any available edition of the "Reportatio". 

Without any further guidance, I would have no way to distinguish between them. If I chose the 1522 edition and then ran my statistical analysis on the transcription that represents it, I would get results that reflect a drastically shortened text.

Therefore, I need the CTS Work to list first available "FRBR Expressions". I then I would like FRBR Expressions to list available CTS Versions or FRBR Manifestations for each FRBR Expression. 

Further, I might want to compare the sizes of the "Reportatio" to the size of the "Abbreviatio". I need to be able to request a Version or Manifestation of each type of Expression.

You might think. Well we can solve this by simply declaring each of these as a different CTS Work or FRBR Work. 

But now I have lost of a connection between the "Reportatio" and the "Abbreviatio." Now it will be seen as just another Work by Adam Wodeham, alongside all of his works. And if, I said, show me all the works written by Wodeham I would have very misleading results if it returned, "Lectura Secunda (another earlier work by Wodeham), Oxford Ordinatio/Reportatio, and Abbreviatio. (It would know look like he wrote three works, when he really only wrote two.)

Finally, what if I, as a user, have no knowledge of this deep complexity? What if all I know about is the fact that Adam Wodeham wrote the Oxford Ordinatio and I want to get the transcription that reflects what scholars consider the best representation of this text?

In this case, I would like to see each CTS Work / FRBR work point to a `canonicalExpression` so that my client application knows what Expression to default to. 

Correspondingly, I think each expression should have a `canonicalManifestation` (or `canonicalCTSVersion`) so a "dumb" client knows which CTS Version or FRBR Manifestation to use. 

Finally since each CTS Version or FRBR Manifestation could be have multiple "transcriptions" understood as a special type of CTS Exempar or FRBR Item, each manifestation should point to a canonicalTranscription (which is a kind of CTS Exemplar or FRBR Item -- but one that represents a digital file rather than a material object) so that my dumb client can know which transcription to use. 

If we don't want the client to have to drill down through the entire FRBR/CTS tree, we might even allow a "canonicalTranscription" property on the Work itself so that a REALLY DUMB client, could find a TEI file in one link from the Work itself.

So in this user case, where my user only knows about Wodeham's Ordinatio and wants to move directly to a useable TEI transcription, they could bypass all the complexity mentioned above and move in one link to the canonicalTranscription and then move via a "hasTei" property to the text itself.

This is not an isolated use case in the Medieval World. "Abbreviationes" and "First, Second, and Third Redactions" abound.

**Comment by balmas** [comment]
I think the spec fully supports this, so I'm closing.
