### ISSUE TITLE
Discover which version of a transcription should be the default transcription

### ISSUE THREAD

**Issue by jeffreycwitt** [distributed-text-services/collection-api#19]
I anticipate releasing different versions of my TEI transcriptions of the same manuscript over time (1.0.0, 2.0.0, etc) (note that this is a different use of the word "version" and should be distinguished from the unfortunate CTS use of the word Version).

Thus when I look up a particular (FRBR ITEM / or CTS Exemplar) I want to be informed about the available transcriptions of that item: 

so for example:
- hasTranscription --> 1.0.0
- hasTranscription --> 2.0.0
- hasTranscription --> master

I also want to be informed about which transcription should be used as the default transcription, so something like: 
- hasCanonicalTranscription --> 2.0.0

**Comment by PonteIneptique** [comment]
Updating the title to make it wider.

**Comment by balmas** [comment]
@jeffreycwitt please verify that this requirement is met by the hasRoles Collection capability and the role property in the MemberItemMappingMetadata .

**Comment by jeffreycwitt** [comment]
sure, that'll probably work.
