### ISSUE TITLE
Versioning of resources (FRBR Item) should be optional

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#21]
## User story
- **A project with user input** cannot **afford resource versioning** but **wants to support DTS**
- **A project with huge data set** cannot **afford resource versioning** but **wants to support DTS**
## Example

Right now, Perseus does not support CTS exemplar/FRBR Version because it is just too heavy to support. 
## Requirement

There should be a flag to indicate support of exemplar for API users to be aware.

**Comment by jeffreycwitt** [comment]
Thibault,

Do you mean FRBR Item? FRBR doesn't have a concept called Version and I believe a CTS exemplar parallels to a FRBR Item. 

See: 

>The CTS URN’s version corresponds to the “expression” in the FRBR model, while exemplars correspond to “items” in FRBR parlance. At the “version” level, a text may be an “edition” of the notional “work”, that is, a version of the work in the language in which the work was originally composed. A version in any other language is a translation. The CTS URN does not distinguish between editions and translation; they are both expressed by version-level URNs. http://cite-architecture.github.io/ctsurn/overview/

and Issues #15

**Comment by PonteIneptique** [comment]
Fixed

**Comment by balmas** [comment]
The spec supports this.
