### ISSUE TITLE
Use Case Categorization

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#22]
@fbaumgardt and @ponteineptique
- [x] Categorization Map
- [ ] Explain categorization of use case
- [ ] Explain categorization of data type
- [ ] Map proposed categorization to CTS as an example

**Comment by PonteIneptique** [comment]
@fbaumgardt Can you upload in this repo your map ?

**Comment by balmas** [comment]
I'm guessing we aren't going to do any more on this right now, so closing.  @fbaumgardt and @PonteIneptique feel free to reopen if you want to tackle further.
