### ISSUE TITLE
dts:size and dts:members

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#37]
Hey @hcayless , still going through your proposal :+1: 

- in `dts:members` you have an array of dict with `dts:id`. I would believe keeping it @id JSON-LD like (aka RDF:Id) would be better.
- is `dts:size` the side of descendants or children or descendant-and-self (xpath meaning of these)
- in the meeting, we discussed the difference between so called stable IDs and resource uri. I don't see it in this proposal. I would propose a `'dts:host': ["http://url.com/api/dts/collection/idoftheresource"]` which would allow to display multiple host if necessary. Another simple option would be anything like `dts:uri` and treat `dts:host` with a `owl:sameAs` instead of creating a new meaning.

**Comment by hcayless** [comment]
`@id` is fine. I deliberately didn't do any JSON-LD context in the proposal, and the proposal is not proper JSON either, really just for the sake of readability.

`dts:size` I was imagining as the count of the children in members. It's there both as metadata and as an aid to paging large collections. It's really "hit count".

I think the third point is good, but warrants more thought and discussion.

**Comment by balmas** [comment]
re dts:host, it might be instructive to look at what the Web Annotation spec does here:

"Example Use Case: Petra creates an Annotation and sends it to multiple systems to maintain, one personal and one public. She wants to ensure that the copies can be aligned, and so she sets a UUID as the canonical IRI, allowing the service to assign an HTTP IRI for it. A subsequent system then harvests the public copy, maintaining the canonical UUID as discovered, then moves the original HTTP IRI to via, replacing it with an IRI under its control. "
```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.org/anno17",
  "type": "Annotation",
  "canonical": "urn:uuid:dbfb1861-0ecf-41ad-be94-a584e5c4f1df",
  "via": "http://other.example.org/anno1",
  "body": {
    "id": "http://example.net/review1",
    "rights": "http://creativecommons.org/licenses/by/4.0/"
  },
  "target": "http://example.com/product1"
}
```

**Comment by PonteIneptique** [comment]
Things made clearer for size and members to some extent. Other fixed by https://github.com/distributed-text-services/collection-api/blob/master/minutes/25.01.2017.md
