### ISSUE TITLE
CTS Into DTS 

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#38]
Hey there,

The whole thing is mostly implemented in MyCapytain as export (waiting for the complete decision to write the import). Here is the thing I got : 

```json
{
   "@graph":{
      "dts:size":2,
      "dts:parents":[
         {
            "@id":"urn:cts:latinLit:phi0959",
            "dts:url":"urn:cts:latinLit:phi0959",
            "rdfs:label":{
               "@lang":"eng",
               "@value":"Ovid"
            }
         },
         {
            "@id":"",
            "dts:url":"",
            "rdfs:label":""
         }
      ],
      "dts:members":[
         {
            "@id":"urn:cts:latinLit:phi0959.phi005.perseus-eng2",
            "dts:url":"urn:cts:latinLit:phi0959.phi005.perseus-eng2",
            "rdfs:label":{
               "@lang":"eng",
               "@value":"Remedia Amoris, The Art of Love in Three Books The remedy of love. The\n      art of beauty. The court of love. The history of love amours."
            }
         },
         {
            "@id":"urn:cts:latinLit:phi0959.phi005.perseus-lat2",
            "dts:url":"urn:cts:latinLit:phi0959.phi005.perseus-lat2",
            "rdfs:label":{
               "@lang":"eng",
               "@value":"Remedy of Love"
            }
         }
      ],
      "@id":"urn:cts:latinLit:phi0959.phi005",
      "rdfs:label":{
         "@lang":"lat",
         "@value":"Remedia amoris"
      },
      "dts:metadata":{
         "skos:prefLabel":[
            {
               "@lang":"eng",
               "@value":"Remedy of Love"
            },
            {
               "@lang":"fre",
               "@value":"Rem\u0102\u00a8de \u0102\u00a0 l'amour"
            },
            {
               "@lang":"lat",
               "@value":"Remedia amoris"
            }
         ],
         "title":[
            {
               "@lang":"lat",
               "@value":"Remedia amoris"
            },
            {
               "@lang":"eng",
               "@value":"Remedy of Love"
            },
            {
               "@lang":"fre",
               "@value":"Rem\u0102\u00a8de \u0102\u00a0 l'amour"
            }
         ]
      }
   },
   "@context":{
      "dts":"http://w3id.org/dts-ontology/",
      "":"http://chs.harvard.edu/xmlns/cts/",
      "rdfs":"http://www.w3.org/2000/01/rdf-schema#",
      "ns1":"http://purl.org/dc/elements/1.1/",
      "rdf":"http://www.w3.org/1999/02/22-rdf-syntax-ns#",
      "skos":"http://www.w3.org/2004/02/skos/core#"
   }
}
```

out of  

```python
from MyCapytain.retrievers.cts5 import CTS
from json import dump
from MyCapytain.common.constants import Mimetypes
from MyCapytain.resources.collections.cts import TextInventory

c = CTS("http://cts.perseids.org/api/cts/")
a = TextInventory.parse(resource=c.getCapabilities(urn="urn:cts:latinLit:phi0959"))
with open("./inv", "w") as f:
    dump(a["urn:cts:latinLit:phi0959.phi005"].export(Mimetypes.JSON.DTS.Std), f)
```

There is bugs here and there (like the id of inventory and its label are failing) but it should be the DTS equivalent of http://cts.dh.uni-leipzig.de/api/cts/?request=GetCapabilities&urn=urn:cts:latinLit:phi0959.phi005 into dts.

I feel like `@type` for parents and members is missing, as well as for the current object :)

**Comment by balmas** [comment]
This looks pretty good to me.  There are a few things missing I agree.

1. Re @type for parents and members, the original proposal had a dts:properties object at the top level which defined the type of subject of the current response and its license.  This could be flattened out of a properties object but I think it still needs to be there.

```
  "dts:properties": {
      "rdf:type": "http://homermultitext.org/rdfvocab/work",
      "dc:license": "https://creativecommons.org/licenses/by-sa/3.0/"
    },
```

2. I'd really like to see the capabilities object back in there -- this is how I envisioned consumers would be able to know what they can actually do with the collection. The original proposal had, e.g.

```
    "dts:capabilities": {
      "dts:ordered": false,
      "dts:supportsRoles": true,
      "dts:static": false, // means additional editions/translations may be added
      "dts:navigation": {
        "dts:parents": [
          {
            "@id": "urn:cts:latinLit:phi1294",
            "rdf:type": "http://homermultitext.org/rdfvocab/textgroup",
            "dts:model": "http://w3id.org/dts-ontology/collection"
          }
        ],
        "dts:siblings": {}
      }
    },
```
@hcayless suggested condensing that to something like:

```
dts:capabilities: {
  dts:sortable: {<paramName>:[<dts:metadata/property label>, ...]}
  dts:searchable {<paramName>:[<dts:metadata/property label>, ...]}
}
```
moving dts:static to be something that could be implied from a dts:version property at the top level. This is okay with me, but I would like define the things that we think are likely to constrain or expand the actions available on the collection and express those via capabilities.

3. The other thing missing both from this and from @hcayless version at https://github.com/distributed-text-services/API/wiki/Collections-API-Proposal-Notes is the identification of the collection model and the ontology used for descriptive metadata.

**Comment by PonteIneptique** [comment]
I am not sure to understand the third.
I think this is a really nice thing to discuss these details before the next meeting.
FYI, capabilities is not implemented in here because this is not an API but a conversion of metadata. The API is responsible for its own capabilities I'd guess :)

**Comment by balmas** [comment]
the model was so that clients could know whether an item was, e.g. a collection which could be queried for further members, or the lowest level item.  This is distinct from rdf:type, which would tell you whether you were looking at a cts work, or a papyri document, or a scta edition, etc. It's possible it's not needed here, particularly if we're going to split the retrieval of passages (chunks of texts, citations, etc. whatever we call it) into a separate API.   

The idea behind providing an ontology property would be so that clients could know what properties to expect in descriptive metadata.  

Both of these are comes from the more general RDA Collections API work. We could choose to drop them here, but I think they are worth keeping personally.

I'll try to update the swagger spec today based upon what you, @hcayless and Jeffrey have done, and we'll see where that gets us.

**Comment by PonteIneptique** [comment]
Most of the discussion redirected to https://github.com/distributed-text-services/collection-api/blob/master/minutes/25.01.2017.md

I think the question of expected metadata is dealt with through `@graph` though. Up to @balmas to agree with this one... Will see with issue #40
