### ISSUE TITLE
To deal with swagger : two default output, json-ld/compact and json

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#40]
## Status 

The proposal of swagger currently uses a vocabulary to advertise available namespaces for metadata

```json
{
"@id" : "SwaggerCollection",
"vocabulary" : "http://perseus.org/terms",
"metadata": {
  "author": [{"@value": "Bridget", "@lang": "eng"}]
}
}
```

(author would be a term of perseus)

while my implementation used JSON-LD Compact system : 

```json
{
  "@context": {
    "perseus" : "http://perseus.org/terms",
    "" : "http://ontology-dts.org/terms"
  },
  "@graph": [
    {
      "@id" : "SwaggerCollection",
      "metadata": {
        "perseus:author": [{"@value": "Bridget", "@lang": "eng"}]
      }
    }
  ]
}
```

## Proposal
I would suggest to implement a JSON-LD like implementation of our vocabulary for our default response (using prefixes for metadata) and a Json LD expression as well.

**mimetype request header :** `application/json`

```json
{
      "@id" : "SwaggerCollection",
      "@context": {
         "perseus" : "http://perseus.org/terms",
         "" : "http://ontology-dts.org/terms"
      },
      "metadata": {
        "perseus:author": [{"@value": "Bridget", "@lang": "eng"}]
      }
}
```

**mimetype request header :** `application/ld+json`

```json
{
  "@context": {
    "perseus" : "http://perseus.org/terms",
    "" : "http://ontology-dts.org/terms"
  },
  "@graph": [
    {
      "@id" : "SwaggerCollection",
      "metadata": {
        "perseus:author": [{"@value": "Bridget", "@lang": "eng"}]
      }
    }
  ]
}
```

# Advantages and consequences
The transformation and parsing difference is really light. This would also allows for continuing to use SWAGGER ;)

From a python point of view : 

```python
jsonNormal = json.read(b"URI OUTPUT")
jsonLD = {}
jsonLD["@graph"] = jsonNormal
jsonLD["@context"] = jsonNormal["@context"]
del jsonLD["@graph"]["@context"]
```

or in javascript : 

```js
jsonNormal = "AJAX DATA";
jsonLD = {};
jsonLD["@graph"] = jsonNormal;
jsonLD["@context"] = jsonNormal["@context"];
delete jsonLD["@graph"]["@context"];
```

**Comment by PonteIneptique** [comment]
Pinging @jeffreycwitt on top of it

Assigning all of you because you were the more vocals on the question. I would propose a vote or something like this on the issue.

Once we agree on that, I can work the DTS Collection implementation to MyCapytain

**Comment by balmas** [comment]
I'm fine with this.

**Comment by hcayless** [comment]
I'm fine with this too

**Comment by jeffreycwitt** [comment]
agreed :)

**Comment by PonteIneptique** [comment]
For everyone : on top of this question, I would like to know whether you think it's necessary to imply a default namespace relationship between "type" and "label" with respectively RDF and RDFS or would you rather prefix those "rdf:type" and "rdfs:label" ?

**Comment by balmas** [comment]
do you know what is best practice wrt to that? I'm not sure myself.

**Comment by fbaumgardt** [comment]
type has it with @type. label is supposed to be aliased via context: https://github.com/json-ld/json-ld.org/issues/371 <https://github.com/json-ld/json-ld.org/issues/371>. It seems to be alright to alias @label even.

**Comment by PonteIneptique** [comment]
@fbaumgardt would there be anything alike for description ?

**Comment by fbaumgardt** [comment]
It’s not on the list of keywords: http://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords <http://json-ld.org/spec/latest/json-ld/#syntax-tokens-and-keywords>, so the solution would be the same as for label. And I’m not sure whether I’d prefer using @label/@description or rdfs:label/rdf:Description.

**Comment by fbaumgardt** [comment]
FYI, there's a new swagger version incoming: https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/. Don't know how relevant it is, but they added Link headers and changed the JSON implementation. Quote: 

> Now supports more of JSON Schema (oneOf, anyOf, not, nullable, deprecated, writeOnly), and clarifies JSON References a bit

**Comment by balmas** [comment]
Those all sounds like very good enhancements. Upgrading to that will change the instructions here I provided, but it's all for the good. In particular, I think the links feature might address some of the lingering concerns the group has about how to instruct clients about navigation among collection items.  

We should probably decide as a group if we want to upgrade now or wait until the first round of our API specification is complete and implemented. I will add it to the list of discussion items. Thanks Frederik.

**Comment by balmas** [comment]
we agreed to implement this. passing to PR stage.

**Comment by robinsonkwame** [comment]
Did this ever go anywhere? This issue and the new `links` keyword remind me of the [W3C Hydra effort](http://www.hydra-cg.com/) in some ways.

**Comment by PonteIneptique** [comment]
Hey,
This was resolved by moving forward to Hydra back in the days ;)
