### ISSUE TITLE
Navigation API

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/collection-api#68]
_From @jonathanrobie on September 9, 2017 21:37_

The navigation API needs to be completed.

_Copied from original issue: distributed-text-services/distributed-text-services.github.io#7_

**Comment by balmas** [comment]
_From @PonteIneptique on September 14, 2017 7:15_

A first draft was proposed in my amended version : https://github.com/distributed-text-services/distributed-text-services.github.io/wiki/Distributed-Text-Services-API-Proposal-Thibault-Amends#navigation-todo


### Query Parameters

| name | description                              | methods |
|------|------------------------------------------|---------|
| id   | identifier for a document |  GET    |
| passage | passage identifier (used together with `id`) | GET    |
| level | Depth for passages we want to retrieve identifiers of  | GET    |

### Response Headers

The answer comes with the following headers :

| name | description |
|------|-------------|
| Link | Gives relation to next and previous pages |

**Comment by balmas** [comment]
_From @PonteIneptique on September 14, 2017 7:28_

In issue #9 , @jonathanrobie and @hcayless have mentioned directions : 

> ancestors, parent, siblings, following siblings, preceding siblings, or all descendants

I see the following list of parameters, adding on top of the direction "children"

| Name | Description                              | Methods |
|------|------------------------------------------|---------|
| level | (default = 0) Depth for passages we want to retrieve identifiers of  | GET    |
| direction | (Default : children) Direction in which to retrieve  | GET    |
| type  | (Optional) Type of the level to filter one, whatever the depth is. Types are declared in collection's metadata   | GET    |
| groupby | (Optional) Create range of references  | GET    |
| limit | (Optional) Limits the number of result  | GET    |
| semantic | (Optional) Retrieve the typename of the passages as well as the passage reference  | GET    |

Note : urn:cts:greekLit:tlg0012.tlg001.opp-grc5 is the Iliad

- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5` returns the list of reference available at `depth=0` and `direction=children`. This would be the list of books of the Iliad
- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&passage=1` returns the list of reference available at `depth=0` and `direction=children` of `passage=1`. This would be the list of verses of the Iliad (In this option, depth is relative. We can set it to be absolute)
- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&type=verse&direction=descendants&groupby=30` returns the list of all passages that are verse and would group them by 30.

**Comment by balmas** [comment]
_From @PonteIneptique on September 14, 2017 7:37_

Response could be built around 

- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&passage=1` 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.perseus-grc2",
    "passage": ["1.1",  "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12",  "1.13", "1.14", "1.15",  "1.16", "1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24", "1.25", "1.26", "1.27", "1.28", "1.29", "1.30", "1.31", "1.32", "1.33", "1.34", "1.35"]
}
```
- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&limit=10&direction=descendants&semantic` 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.perseus-grc2",
    "passage": [
        {"@type": "book", "@id": "1"},
        {"@type": "verse", "@id": "1.1"},
        {"@type": "verse", "@id": "1.2"},
        {"@type": "verse", "@id": "1.3"},
        {"@type": "verse", "@id": "1.4"},
        {"@type": "verse", "@id": "1.5"},
        {"@type": "verse", "@id": "1.6"},
        {"@type": "verse", "@id": "1.7"},
        {"@type": "verse", "@id": "1.8"},
        {"@type": "verse", "@id": "1.9"},
    ]
}
```

**Comment by jeffreycwitt** [comment]
I'm still struggling to understand why both a document id and passage id are required. 

Are passage ids relative to a given document, such that a passage id can only be found when a separate document id is also given.

It seems to me that every passage should carry with it enough metadata to be discovered by itself. In other words, why isn't enough simply to provide the dts document/passage service with the passage id and receive the passage in response.

What counts as a document or passage seems like relative concept. I can make a TEI file/document at any level of the text hierarchy. From previous discussions, I've gleaned that a "passage" would be  a fragment within that file.

But in this case a fragment can also be a document, and thus providing the document id in which the passage can be found seems arbitrary. If the passage is a fragment at level 3, do I provide the id for the document at level 1 or level 2. And why is this necessary since, the id from the fragment at level 3 should already know in which document (or documents) it is contained.

An example: 

Suppose I have this hierarchy
```
-plaoulcommentary (level 1)
--Section/pp-deFide (level 2)
---lectio1 (level 3)
----paragraph1 (level 4)
```

I can request a TEI document at every level 
```
-plaoulcommentary (http://exist.scta.info/exist/apps/scta-app/document/plaoulcommentary/critical/transcription)
--Section/pp-deFide (http://exist.scta.info/exist/apps/scta-app/document/pp-deFide/critical/transcription - this level isn't working right now)
---lectio1 (http://exist.scta.info/exist/apps/scta-app/document/lectio1/critical/transcription)
----paragraph1 (http://exist.scta.info/exist/apps/scta-app/document/l1-cpspfs/critical/transcription)
```
So if paragraph 1 is my "passage", what is the document?

**Comment by jonathanrobie** [comment]
> Are passage ids relative to a given document, such that a passage id can only be found when a separate document id is also given.

Yes.

> It seems to me that every passage should carry with it enough metadata to be discovered by itself. In other words, why isn't enough simply to provide the dts document/passage service with the passage id and receive the passage in response.

That would require us to redundantly expand the passage id with the document id.  Keeping them separate, we simply say that a passage is identified by the (document id, passage id) pair.

**Comment by jonathanrobie** [comment]
> I see the following list of parameters, adding on top of the direction "children"
> 
> Name	Description	Methods
> level	(default = 0) Depth for passages we want to retrieve identifiers of	GET
> direction	(Default : children) Direction in which to retrieve	GET
> type	(Optional) Type of the level to filter one, whatever the depth is. Types are declared in collection's metadata	GET
> groupby	(Optional) Create range of references	GET
> limit	(Optional) Limits the number of result	GET
> semantic	(Optional) Retrieve the typename of the passages as well as the passage reference

How much of this belongs to the "minimum required to declare victory", if we want to keep the first release as simple as needed?

**Comment by PonteIneptique** [comment]
Currently, CTS supports : 
- `level`
- `direction=descendants` (default)
- `groupby` but this one is tricky : CTS supports it when you ask a range. If you ask a passage range say line 25-34 (so 10 lines), you'll get citations in group of 10.

**Comment by PonteIneptique** [comment]
I think `limit` (and so pagination) is simple to implement though.

**Comment by jonathanrobie** [comment]
Here's one possible set of names ...

- `level`
- `offset`
- `size`
- `n`

**Comment by balmas** [comment]
I prefer:
* level
* offset
* chunkSize
* max

**Comment by jonathanrobie** [comment]
Closing the issue: we will use the query parameters Bridget proposed in the previous comment.
