### ISSUE TITLE
Hydra-Collection's Collection Metadata Example

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#73]
Hey @jonathanrobie 
As discussed at the end of today's meeting, it would be great to have an hydra collection implementation example. I think two separate kind of examples would be great: 
- a first one based on one of your texts
- a second one which would reflect the three different collections described here (I can help reading the CTS response if needed): http://cts.dh.uni-leipzig.de/api/cts?request=GetCapabilities&urn=urn:cts:latinLit:phi1294 (Textgroup, work and edtion nodes represent the three in-hierarchy collections)

That might set flags if we have an issue with the response format but mostly I find that standards without simple examples are hard to implement...

**Comment by balmas** [comment]
I still would like to urge consideration of the RDA Collections API data model too. https://github.com/RDACollectionsWG/specification

**Comment by PonteIneptique** [comment]
I think the Collection API Response format has to follow the following requirements, based on our oldest discussions :

- Response Format should described Collections with DC and DCT ontologies, with mandatory titles ( https://github.com/distributed-text-services/collection-api/issues/52 )
- Response Format should allow to navigate to children and parent collections
   - It should be possible to have minimal information about children and parent (dc:title at least)
- Response Format should allow to embed other ontologies
   - It should however stays simple : depth of the tree for description should remain low ( https://github.com/distributed-text-services/collection-api/issues/42 )
- Response Format should tell if the Collection can be downloaded ( https://github.com/distributed-text-services/collection-api/issues/56 )
- Response Format should tell if the Collection can be Navigated on ( https://github.com/distributed-text-services/collection-api/issues/56 )
   - Response Format should indicate the citation scheme (Though I am lost on this one for the original discussion)
- Response Format should  tell if the Collection can be read ( https://github.com/distributed-text-services/collection-api/issues/56 )

That's all that still makes sense to me after the whole set of discussion over the last years...

**Comment by PonteIneptique** [comment]
Issues with the RDA Collection API is that it enforces a URI scheme and this way is unable to support full URIs identifier such as `www.scta.org/somepath/somesecondpath/idofmytext`

**Comment by balmas** [comment]
hmm. yes, I suppose that's true, although that could probably be addressed with proxies. But ok.

**Comment by PonteIneptique** [comment]
For future reference, here is a simple representation of the GetCapabilities request I posted on the first comment
![metadata of cts](https://user-images.githubusercontent.com/1929830/35442870-0a1ac6de-02a9-11e8-8a7d-c73a2399d608.png)

**Comment by PonteIneptique** [comment]
As other useful logs of our discussion with @jonathanrobie : 

Based on [the original example given in the repository](https://github.com/distributed-text-services/collection-api/blob/master/distributed-text-services-api.md#hydra-representation-and-hierarchy)  

```json
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@id": "urn:perseus:collections",
  "@type": "Collection",
  "totalItems": "2",
  "member": [
    {
      "@id": "urn:perseus:greekLit",
      "title" : "Ancient Greek"
    },
    {
      "@id": "urn:perseus:latinLit",
      "title": "Classical Latin"
    },
    ...
  ]
}
```

And the needs of CTS and the one discussed earlier displayed in this issue, here are the currently questions regarding Hydra  : 
1. for collections listed in "member", can we have a "@type"
2. for collections listed in "member", can we have a "childrenCount" or something alike
3. for collections listed in member, can you deal with i18n of names
4. for main collection, can you add more details (example dc:contributor, schema:birthDate, etc.)
5. for main collection, if it were a child of another, how would this be displayed
6. for collections in general, how do you display the fact it's :
   a. readable (in Passage API)
   b. navigable (in Navigation API)
   c. downloaded (in any other way)
7. how could we implement something to translate the CTS citationMapping

**Comment by PonteIneptique** [comment]
Regarding 7., one proposal I made (which we can keep for the sake of the discussion) on which we did not have a discussion (this will wait further research) : 

```json
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@id": "urn:cts:latinLit:phi1294.phi002.perseus-lat2",
  "@type": "Collection",
  "title": "Epigrammata",
   "description": "Edition by X digitized by Perseus",
   "tei:refsDecl": [
      {"tei:matchPattern":  "\w+", "tei:replacementPattern": "#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])", "@type": "book"},
      {"tei:matchPattern":  "\w+\.\w+", "tei:replacementPattern": "#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])", "@type": "poem"},
      {"tei:matchPattern":  "\w+\.\w+\.\w+", "tei:replacementPattern": "#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2']//tei:l[@n='$3'])", "@type": "line"}
   ]
...
}
```

**Comment by PonteIneptique** [comment]
Here is an implementation draft to include the User Requirements we have up there. This is meant to be discussed, including the syntax. I'd prefer that we have our own, described context but I am afraid of collision between things (such as dc:title and hydra:title) : https://github.com/PonteIneptique/dts-response-format/blob/master/collection-api/example1.md

We can probably talk about that together this afternoon @jonathanrobie ?

**Comment by jonathanrobie** [comment]
I'd like to hear people weigh in on what metadata should be required vs. optional.  

I think this kind of construct can be simplified:

```json
"title" : [
	{"@lang": "fre", "@value": "Cartulaires", "default": true},
	{"@lang": "unk", "@value": "Cartularia"},
]```

I prefer something like this:

```json
title: {
	"fre" : "Cartulaires",
	"unk" : "Cartularia"
}```

That will be easier to process and query,  with paths like `title["fre"]`.

**Comment by PonteIneptique** [comment]
I do agree with @jonathanrobie . Then I thought about the collection which can have multiple names/spelling in one language, and the ability to have a default. But I do agree with the "simpler would be better" :)

**Comment by jonathanrobie** [comment]
Is the default up to the client?  I might prefer English or Greek titles by default, you might prefer French titles by default.  I'm not sure that the server should decide which title the user wants to see.

**Comment by PonteIneptique** [comment]
By `default` I would mean `prefered` or `original`. When we are talking about heritage collection, saying "De Rerum Natura" or "De la nature de choses" is not the same, and quoting "Misanthrop" or "Misanthrope" from Moliere is not the same as well. That's a real question about what we want to support, not something I absolutely need ;)

**Comment by jonathanrobie** [comment]
I don't know what the best practice is here.  Some questions:

- Can there ever be more than one preferred or original title?
- I assume you can have a title in a different language from that of the text, e.g. a title like "Greek New Testament"
- Do we need to allow more than one title in a given language?

**Comment by jonathanrobie** [comment]
See this link for URI templates:

https://www.hydra-cg.com/spec/latest/core/#templated-links

**Comment by PonteIneptique** [comment]
I have updated the example with a paginated example. As for the URI templates, they seems quite hard to implement for "member->@id" and looks more overcomplicated than any other thing. Or maybe I am reading the documentation badly.

**Comment by PonteIneptique** [comment]
I am pretty sure we are gonna talk about it during the meeting but I wonder if Hydra is the best model for what we want to do and if saying we want to support Hydra is the best choice. Describing the API is the most important thing, I think we also agreed on most things (like efficiency in answer, linking capacities, etc.) I am not sure building on Hydra is the best choice.

As I am saying that, I do not know what are the best other options ( Swagger / OpenAPI 3.0 ? Json-API ?) I tried to see if we could express our scheme in OpenAPI but it seems rather "hard" to keep the full LD part of the API : https://app.swaggerhub.com/apis/DTService/DTS/0.0.1 (though describing the URI scheme is a wonderful simplicity...)

**Comment by jonathanrobie** [comment]
What are your concerns about Hydra?  These different formats represent
different models, some are RESTful, some are not.  My preference is to use
a format that:

1. Is RESTful
2. Is complete enough that we don't have to invent our own conventions for
things like pagination, URI templates, etc. so that clients know what to do

Hydra and json:api would both work, but at this point in the process, I
would like to have a good reason to switch.  Let's not revisit decisions
without a clear motivation.

**Comment by jonathanrobie** [comment]
In today's meeting we made the following decisions:

Collection. Document metadata:

- required: id, title, type, totalItems
- optional:  dts:dublincore, dts:extensions (contains metadata in other namespaces), dts:references, dts:passage, dts:download  (we may change this name)

Internationalization:

- Hydra's `title`, `description` only allow one one,
- For internationalization, use `dc:title`, `dc:description` - repeatable, allows multiple titles in multiple languages

**Comment by jonathanrobie** [comment]
Closed per today's meeting, accepting decisions from the previous comment.
