### ISSUE TITLE
Response format for Navigation API

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#74]
In order to have simple response formats : 

- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&passage=1` 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.opp-grc5",
    "passage": ["1.1",  "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10", "1.11", "1.12",  "1.13", "1.14", "1.15",  "1.16", "1.17", "1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24", "1.25", "1.26", "1.27", "1.28", "1.29", "1.30", "1.31", "1.32", "1.33", "1.34", "1.35"]
}
```

- GET `/dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&semantic` 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.opp-grc5",
    "passage": [
        {"@type": "book", "@id": "1"},
        {"@type": "verse", "@id": "1.1"},
        {"@type": "verse", "@id": "1.2"},
        {"@type": "verse", "@id": "1.3"},
        {"@type": "verse", "@id": "1.4"},
        {"@type": "verse", "@id": "1.5"},
        {"@type": "verse", "@id": "1.6"},
        {"@type": "verse", "@id": "1.7"},
        {"@type": "verse", "@id": "1.8"},
        {"@type": "verse", "@id": "1.9"},
    ]
}
```

**Comment by editions** [comment]
…and of course, the semantic of the @type attribute (its authorized values) is up to the implementer (?).

**Comment by PonteIneptique** [comment]
Definitely :) You could even use controlled vocabulary here :)

**Comment by balmas** [comment]
A note on the history of this discussion.  There have been some philosophical challenges in agreeing upon whether or not the response should be a full hypermedia response, where all navigation is achieved through links and link relations, or a custom api which is maybe optimized for performance and speed but for which client knowledge of the API is required for use.  Note that such client knowledge could be expressed in shared libraries, which could be pretty easily automatically generated client libraries if something like OpenAPI 3.0 is used to document the API. (For the full painful history, refer to #57, a discussion I think we would all like to forget).

I believe the main concern with the hypermedia approach is the overhead required for transmission of repetitive link information for what might be thousands of passages in the response. Supplying a base url, and a url template, would allow for a shorthand using the passage identifiers.  A compromise approach might be one which supports both options, but which defines the shorthand version as the minimum requirement.

**Comment by PonteIneptique** [comment]
Templating URI has been linked here https://www.hydra-cg.com/spec/latest/core/#templated-links
It is still unclear to me how to move from our response to this and how this makes things easier to understand :) An example would be most welcome @jonathanrobie

**Comment by jonathanrobie** [comment]
Here's an example for the passage API.   Suppose you want requests to use a format like this:

```
GET /dts/api/references/?id=urn:cts:greekLit:tlg0012.tlg001.opp-grc5&passage=1
```

In Hydra, the specification would say which variables are used in the template like this:

```json
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@type": "IriTemplate",
  "template": "/dts/api/references/?id={ctsid}&passage={passageid}",
  "variableRepresentation": "BasicRepresentation",
  "mapping": [
    {
      "@type": "IriTemplateMapping",
      "variable": "ctsid",
      "required": true
    },
    {
      "@type": "IriTemplateMapping",
      "variable": "passageid",
      "required": false
    }
  ]
}
```

The client would use a URI template library to expand the values for the URI parameters.  To expand the template, it would call a function containing the template itself and a JSON structure that specifies the values for the variables.

```json
{
  "ctsid" : "urn:cts:greekLit:tlg0012.tlg001.opp-grc5",
  "passageid" : "1"
}
```

You can test URI templates here:

https://bigbluehat.github.io/vue-uri/

**Comment by jonathanrobie** [comment]
Are there remaining aspects that need to be resolved for this issue?  Should we close this in favor of more specific issues?  (Let's decide that at tomorrow's meeting.)

**Comment by PonteIneptique** [comment]
If everybody agrees with the response format, I think this issue *in fine* is good. We still need top open an issue about the `semantic` parameter ;)

**Comment by balmas** [comment]
I am fine with this.

**Comment by hcayless** [comment]
Small point: the variable name `ctsid` implies CTS, so maybe we should make it something neutral? I'm fine with using CTS examples, of course.

**Comment by PonteIneptique** [comment]
I think here ctsid was more like an example :) We should definitely name it collection_id is the final draft :)

**Comment by jonathanrobie** [comment]
Closed per today's call.
