### ISSUE TITLE
What's the DTS Namespace URI ?

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#79]

**Comment by balmas** [comment]
I vote for using w31id.org identifiers https://w3id.org/

**Comment by PonteIneptique** [comment]
I am used to purl which allows us to host things where we want but I am not stuck on this choice.

**Comment by jonathanrobie** [comment]
Something like https://w3id.org/api?

**Comment by PonteIneptique** [comment]
https://w3id.org/cts/api ? @balmas @architexte are you okay with that ?

**Comment by hcayless** [comment]
https://w3id.org/dts/api, you mean, right?

**Comment by PonteIneptique** [comment]
I need vacations.

**Comment by hcayless** [comment]
I’ve set the URI above up and for the time being set it to redirect to our GitHub org site. When we have a published spec, we can reset it to go there.
