### ISSUE TITLE
How does the Navigation API provide ranges in its response format

### ISSUE THREAD

**Issue by PonteIneptique** [distributed-text-services/collection-api#81]
We agreed in #75 that we would not set up restricted characters.
In this context, we need to agree on the response format in the navigation API for ranges. The current response format is : 

```json
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.opp-grc5",
    "passage": ["1.1",  "1.2", "1.3"]
}
```

## Option 1
We could go with clear, detailed answer with clear object properties
```
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.opp-grc5",
    "passage": [{"start":"1.1", "end": "1.2"}, {"start":"1.3", "end": "1.4"}]
}
```

## Option 2
We could go with clear, detailed answer with lighter format (list of two identifiers means : start + end)
```
{
    "@base": "/dts/api/document/",
    "@id":"urn:cts:greekLit:tlg0012.tlg001.opp-grc5",
    "passage": [["1.1","1.2"], ["1.3", "1.4"]]
}
```

**Comment by balmas** [comment]
I prefer Option 1

**Comment by jonathanrobie** [comment]
We agreed to Option 1.
