### ISSUE TITLE
add link to BCP47 recommendation to use it

### ISSUE THREAD

**Issue by balmas** [distributed-text-services/collection-api#90]
In our review of the specs @zfletch raised the question of whether the spec calls for 2 or 3 character iso language codes in relevant fields. Should we specify this?

**Comment by PonteIneptique** [comment]
In PR #100 , we merged and decided that all language tags to 2-character form following BCP 47 (according to TEI as well).

We should add a link and this recommendation.

**Comment by jonathanrobie** [comment]
We agreed to do this in today's meeting.
