### ISSUE TITLE
Recommendation for @id in collections API

### ISSUE THREAD

**Issue by hcayless** [distributed-text-services/collection-api#92]
Should we recommend that ids be globally unique URIs? In the current examples, we have both:

```
"@id": "general",
```
and
```
"@id" : "urn:cts:latinLit:phi1103.phi001.lascivaroma-lat1",
```
CTS kind of takes care of this on its own, but maybe we should point out in the spec that if you use a simple string like "general" for a collection name, that collection may not be portable. I would say something like "`@id` *should* be a URI".

**Comment by PonteIneptique** [comment]
That's a good question. To sum up my position on it, I would be in favor of this but I wonder how much not forcing anything about the identifier can open up to other data contributors ?

**Comment by hcayless** [comment]
I don't think it should be mandatory, but I do think we should come up with some language explaining why you'd want to use a globally unique id instead of a local one.

**Comment by PonteIneptique** [comment]
That's a French/English issue here, sorry I missed the difference (I always have difficulties when reading quickly between should / must).
Then I'd definitely be fine to add a little something (maybe outside the APIs description, in the general API informations) ;)

**Comment by hcayless** [comment]
Group seems to agree on this. Let's do it.
