### ISSUE TITLE
Wait on Document, Navigation endpoints before publishing Collection?

### ISSUE THREAD

**Issue by jonathanrobie** [distributed-text-services/collection-api#99]
Should we publish the first drafts of Document and Navigation together with Collection?

That feels important for ensuring that we have thought through the basic functionality for using them together.

**Comment by PonteIneptique** [comment]
My point of view : absolutely. To me, the DTS API (which is weird because the repo is named collection api) is about the whole package and we designed some of the response based on the needs of the two other endpoints.

**Comment by jonathanrobie** [comment]
Agreed - we will wait until we have a good first draft of each.
